### ISSUE TITLE
Web API Global Exceptions Handling

### ISSUE THREAD

**Issue by fehmisener** [Rater-Inc/dotnet-api#34]
### Description:
Implement a global exception handling mechanism for the Web API to ensure that all unhandled exceptions are caught and processed consistently. This will improve the robustness and reliability of the API by providing meaningful error messages and statuses to the clients.

#### Tasks:
1. **Research and Plan**:
   - Investigate best practices for global exception handling in web APIs.
   - Decide on the structure and format of the error responses (e.g., HTTP status codes, error messages, error codes).

2. **Create Custom Exception Classes**:
   - Define custom exception classes for common error scenarios (e.g., `NotFoundException`, `ValidationException`).

3. **Implement Global Exception Handler**:
   - Develop a global exception handler to catch all unhandled exceptions.
   - Ensure the handler logs the exceptions for further analysis and debugging.
   - Map exceptions to appropriate HTTP status codes and error responses.

4. **Middleware Integration**:
   - Integrate the global exception handler into the middleware pipeline to ensure it catches exceptions thrown from any part of the API.

5. **Error Response Format**:
   - Define a consistent error response format.
   - Include relevant details such as error code, message, and any additional information that might help the client understand the error.

 ```json
{
   "success":false,
   "status":"HttpStatusCode.InternalServerError",
   "message":"exception.Message",
   "stackTrace":"exception.StackTrace"
}
```

6. **Logging**:
   - Implement logging for all caught exceptions to facilitate monitoring and debugging.
   - Choose an appropriate logging framework and configure it to log errors consistently.

#### Acceptance Criteria:
- [x] All unhandled exceptions are caught by the global exception handler.
- [x] Error responses follow the defined format and provide meaningful information to clients.
- [x] Exceptions are logged for further analysis and debugging.
- [x] All routes must have this functionality.

**Comment by fehmisener** [comment]
You can refer this page [.NET 6 - Web API Global Exceptions Handling 🌐](https://dev.to/moe23/net-6-web-api-global-exceptions-handling-1a46) and feel free to extend 💯

**Comment by fehmisener** [comment]
We can also think adding GUID to the response object for further log monitoring works.

**Comment by fehmisener** [comment]
Apparently, we still have some work to do on this task. @Sirmelihy
